apiVersion: v2
name: beneficiary-portal
description: A Helm chart for deploying the HOPE Beneficiary Portal
type: application
version: 0.1.0
appVersion: "develop"

dependencies:
  - name: postgresql
    version: "14.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: 18.19.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled