apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hope-beneficiary-portal.fullname" . }}-backend
  labels:
    {{- include "hope-beneficiary-portal.labels" . | nindent 4 }}
data:
{{- range $key, $value :=  .Values.backend.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
