apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beneficiary-portal.fullname" . }}-backend
  labels:
    {{- include "beneficiary-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "beneficiary-portal.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "beneficiary-portal.labels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: {{ include "beneficiary-portal.serviceAccountName" . }}
      containers:
      - name: backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" | quote }}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ include "beneficiary-portal.fullname" . }}-config
        resources:
          {{- toYaml .Values.resources | default "{}" | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health/
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
