apiVersion: v1
kind: Service
metadata:
  name: {{ include "hope-beneficiary-portal.fullname" . }}-backend
  labels:
    {{- include "hope-beneficiary-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
  selector:
    {{- include "hope-beneficiary-portal.selectorLabels" . | nindent 4 }}
    service: "backend"
