{{- if and .Values.flower.enabled .Values.celery.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "beneficiary-portal.fullname" . }}-flower
  labels:
    {{- include "benefitory-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: flower
spec:
  type: {{ .Values.flower.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.flower.service.port }}
      targetPort: {{ .Values.flower.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "beneficiary-portal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: flower
{{- end }}
